# import pandas as pd
# import numpy as np

# DiseaseRules =  {
#     'Urethal Obstruction': {
#     			# No, prob not, dont know, prob, yes
#     		   'Frequent Urination' : [0, 0, 0, 0, 1],
#                'Blood in Urine' : [0, 0, 0, 0, 1],
#                'Painful Urination' : [0, 0, 0, 0, 1],
#                'Licking Genital Area' : [0, 0, 0, 0, 1],
#                'Lethargy and Weakness' : [0, 0, 0, 0, 1],
#                'Straining to Urinate' : [0, 0, 0, 0, 1],
#                'Abdominal Pain' : [0, 0, 0, 0, 1],
#                'Vomiting and Nausea' : [0, 0, 0, 0, 1],
#                'Polydipsia' : [0, 0, 1, 0, 0],
#                'Limping' : [0, 0, 1, 0, 0],
#                'Swelling members' : [1, 0, 0, 0, 0],
#                'Fever' : [0, 0, 1, 0, 0],
#                'Loss Appetite' : [0, 0, 0, 0, 1],
#                'Weight loss' : [0, 0, 1, 0, 0],
#                'PotBellied Appearance' : [0, 0, 1, 0, 0],
#                'Diarrhea' : [0, 0, 1, 0, 0],
#                'Constipation' : [0, 0, 1, 0, 0],
#                'Visible Worms' : [0, 0, 1, 0, 0],
#                'Anal Itching or Scooting' : [0, 0, 1, 0, 0],
#                'Intense itching and scratching' : [0, 0, 1, 0, 0],
#                'Hair loss or thinning of fur' : [0, 0, 1, 0, 0],
#                'Formation of small raised bumps or pustules' : [0, 0, 1, 0, 0],
#                'Irritated or weepy eyes' : [0, 0, 1, 0, 0],
#                'Restlessness and Agitation' : [0, 0, 0, 0, 1],
#                'Over-Grooming' : [0, 0, 1, 0, 0],
#                'Presence of fleas' : [0, 0, 1, 0, 0],
#                'Ear Infection' : [0, 0, 1, 0, 0],
#                'Overweight': [0, 0, 1, 0, 0],
#                'Age': [0, 1, 1, 1, 1],
#                'Vaccination updated': [0, 0, 1, 0, 0],
#                'Male': [0, 0, 0, 0, 1],
#                'Indoor': [0, 0, 1, 0, 0],
#                'Contact with other pets': [0, 0, 1, 0, 0],
#                'Neutered': [0, 0, 1, 0, 0],
#                'Start of the symptoms': [1, 1, 0, 0, 0],
#                'Processed Diet': [0, 0, 1, 0, 0],

#     },
#     'Feline Lower Urinary Tract Disease': {
#     		   'Frequent Urination' : [0, 0, 0, 0, 1],
#                'Blood in Urine' : [0, 0, 0, 0, 1],
#                'Painful Urination' : [0, 0, 0, 0, 1],
#                'Licking Genital Area' : [0, 0, 0, 0, 1],
#                'Lethargy and Weakness' : [0, 0, 0, 0, 1],
#                'Straining to Urinate' : [0, 0, 0, 0, 1],
#                'Abdominal Pain' : [0, 0, 1, 0, 0],
#                'Vomiting and Nausea' : [0, 0, 1, 0, 0],
#                'Polydipsia' : [0, 0, 1, 0, 0],
#                'Limping' : [0, 0, 1, 0, 0],
#                'Swelling members' : [0, 0, 1, 0, 0],
#                'Fever' : [0, 0, 1, 0, 0],
#                'Loss Appetite' : [0, 0, 1, 0, 0],
#                'Weight loss' : [0, 0, 1, 0, 0],
#                'PotBellied Appearance' : [0, 0, 1, 0, 0],
#                'Diarrhea' : [0, 0, 1, 0, 0],
#                'Constipation' : [0, 0, 1, 0, 0],
#                'Visible Worms' : [0, 0, 1, 0, 0],
#                'Anal Itching or Scooting' : [0, 0, 1, 0, 0],
#                'Intense itching and scratching' : [0, 0, 1, 0, 0],
#                'Hair loss or thinning of fur' : [0, 0, 1, 0, 0],
#                'Formation of small raised bumps or pustules' : [0, 0, 1, 0, 0],
#                'Irritated or weepy eyes' : [0, 0, 1, 0, 0],
#                'Restlessness and Agitation' : [0, 0, 0, 0, 1],
#                'Over-Grooming' : [0, 0, 1, 0, 0],
#                'Presence of fleas' : [0, 0, 1, 0, 0],
#                'Ear Infection' : [0, 0, 1, 0, 0],
#                'Overweight': [0, 0, 0, 0, 1],
#                'Age': [0, 1, 1, 1, 1],
#                'Vaccination updated': [0, 0, 1, 0, 0],
#                'Male': [0, 0, 1, 0, 0],
#                'Indoor': [0, 0, 1, 0, 0],
#                'Contact with other pets': [0, 0, 1, 0, 0],
#                'Neutered': [0, 0, 1, 0, 0],
#                'Start of the symptoms': [0, 0, 1, 0, 0],
#                'Processed Diet': [0, 0, 1, 0, 0],

#     },
#     'Renal Disease': {
#     		   'Frequent Urination' : [0, 0, 0, 0, 1],
#                'Blood in Urine' : [0, 0, 1, 0, 0],
#                'Painful Urination' : [0, 0, 1, 0, 0],
#                'Licking Genital Area' : [0, 0, 1, 0, 0],
#                'Lethargy and Weakness' : [0, 0, 0, 0, 1],
#                'Straining to Urinate' : [1, 0, 0, 0, 0],
#                'Abdominal Pain' : [1, 0, 0, 0, 0],
#                'Vomiting and Nausea' : [0, 0, 0, 0, 1],
#                'Polydipsia' : [0, 0, 0, 0, 1],
#                'Limping' : [0, 0, 1, 0, 0],
#                'Swelling members' : [0, 0, 0, 0, 1],
#                'Fever' : [0, 0, 1, 0, 0],
#                'Loss Appetite' : [0, 0, 0, 0, 1],
#                'Weight loss' : [0, 0, 0, 0, 1],
#                'PotBellied Appearance' : [0, 0, 0, 0, 1],
#                'Diarrhea' : [0, 0, 1, 0, 0],
#                'Constipation' : [0, 0, 1, 0, 0],
#                'Visible Worms' : [0, 0, 1, 0, 0],
#                'Anal Itching or Scooting' : [0, 0, 1, 0, 0],
#                'Intense itching and scratching' : [0, 0, 1, 0, 0],
#                'Hair loss or thinning of fur' : [0, 0, 1, 0, 0],
#                'Formation of small raised bumps or pustules': [0, 0, 1, 0, 0],
#                'Irritated or weepy eyes' : [0, 0, 1, 0, 0],
#                'Restlessness and Agitation' : [0, 0, 1, 0, 0],
#                'Over-Grooming' : [0, 0, 1, 0, 0],
#                'Presence of fleas' : [0, 0, 1, 0, 0],
#                'Ear Infection' : [0, 0, 1, 0, 0],
#                'Overweight': [0, 0, 1, 0, 0],
#                'Age': [0, 0, 0, 1, 1],
#                'Vaccination updated': [0, 0, 1, 0, 0],
#                'Male': [0, 0, 1, 0, 0],
#                'Indoor': [0, 0, 1, 0, 0],
#                'Contact with other pets': [0, 0, 1, 0, 0],
#                'Neutered': [0, 0, 1, 0, 0],
#                'Start of the symptoms': [1, 0, 0, 0, 0],
#                'Processed Diet': [0, 0, 1, 0, 0],

#     },
#     'Luxation': {
#     		   'Frequent Urination' : [0, 0, 1, 0, 0],
#                'Blood in Urine' : [0, 0, 1, 0, 0],
#                'Painful Urination' : [0, 0, 1, 0, 0],
#                'Licking Genital Area' : [0, 0, 1, 0, 0],
#                'Lethargy and Weakness' : [0, 0, 1, 0, 0],
#                'Straining to Urinate' : [0, 0, 1, 0, 0],
#                'Abdominal Pain' : [0, 0, 1, 0, 0],
#                'Vomiting and Nausea' : [0, 0, 1, 0, 0],
#                'Polydipsia' : [0, 0, 1, 0, 0],
#                'Limping' : [0, 0, 0, 0, 1],
#                'Swelling members' : [0, 0, 0, 0, 1],
#                'Fever' : [0, 0, 1, 0, 0],
#                'Loss Appetite' : [0, 0, 0, 0, 1],
#                'Weight loss' : [0, 0, 1, 0, 0],
#                'PotBellied Appearance' : [0, 0, 1, 0, 0],
#                'Diarrhea' : [0, 0, 1, 0, 0],
#                'Constipation' : [0, 0, 1, 0, 0],
#                'Visible Worms' : [0, 0, 1, 0, 0],
#                'Anal Itching or Scooting' : [0, 0, 1, 0, 0],
#                'Intense itching and scratching' : [0, 0, 1, 0, 0],
#                'Hair loss or thinning of fur' : [0, 0, 1, 0, 0],
#                'Formation of small raised bumps or pustules' : [0, 0, 1, 0, 0],
#                'Irritated or weepy eyes' : [0, 0, 1, 0, 0],
#                'Restlessness and Agitation' : [0, 0, 1, 0, 0],
#                'Over-Grooming' : [0, 0, 1, 0, 0],
#                'Presence of fleas' : [0, 0, 1, 0, 0],
#                'Ear Infection' : [0, 0, 0, 0, 0],
#                'Overweight': [0, 0, 1, 0, 0],
#                'Age': [0, 0, 0, 0, 0],
#                'Vaccination updated': [0, 0, 1, 0, 0],
#                'Male': [0, 0, 1, 0, 0],
#                'Indoor': [1, 0, 0, 0, 0],
#                'Contact with other pets': [0, 0, 0, 0, 1],
#                'Neutered': [0, 0, 1, 0, 0],
#                'Start of the symptoms': [0, 0, 0, 0, 1],
#                'Processed Diet': [0, 0, 1, 0, 0],

#     },
#     'Panleukopenia': {
#     		   'Frequent Urination' : [0, 0, 1, 0, 0],
#                'Blood in Urine' : [0, 0, 1, 0, 0],
#                'Painful Urination' : [0, 0, 1, 0, 0],
#                'Licking Genital Area' : [0, 0, 1, 0, 0],
#                'Lethargy and Weakness' : [0, 0, 0, 0, 1],
#                'Straining to Urinate' : [0, 0, 1, 0, 0],
#                'Abdominal Pain' : [0, 0, 0, 0, 1],
#                'Vomiting and Nausea' : [0, 0, 0, 0, 1],
#                'Polydipsia' : [0, 0, 0, 0, 1],
#                'Limping' : [0, 0, 1, 0, 0],
#                'Swelling members' : [0, 0, 1, 0, 0],
#                'Fever' : [0, 0, 0, 0, 1],
#                'Loss Appetite' : [0, 0, 0, 0, 1],
#                'Weight loss' : [0, 0, 0, 0, 1],
#                'PotBellied Appearance' : [0, 0, 1, 0, 0],
#                'Diarrhea' : [0, 0, 0, 0, 1],
#                'Constipation' : [1, 0, 0, 0, 0],
#                'Visible Worms' : [0, 0, 1, 0, 0],
#                'Anal Itching or Scooting' : [0, 0, 1, 0, 0],
#                'Intense itching and scratching' : [0, 0, 1, 0, 0],
#                'Hair loss or thinning of fur' : [0, 0, 1, 0, 0],
#                'Formation of small raised bumps or pustules' : [0, 0, 1, 0, 0],
#                'Irritated or weepy eyes' : [0, 0, 0, 0, 1],
#                'Restlessness and Agitation' : [0, 0, 1, 0, 0],
#                'Over-Grooming' : [0, 0, 1, 0, 0],
#                'Presence of fleas' : [0, 0, 1, 0, 0],
#                'Ear Infection' : [0, 0, 1, 0, 0],
#                'Overweight': [0, 0, 1, 0, 0],
#                'Age': [1, 1, 0, 0, 0],
#                'Vaccination updated': [1, 0, 0, 0, 0],
#                'Male': [0, 0, 1, 0, 0],
#                'Indoor': [1, 0, 0, 0, 0],
#                'Contact with other pets': [0, 0, 0, 0, 1],
#                'Neutered': [0, 0, 1, 0, 0],
#                'Start of the symptoms': [0, 0, 0, 0, 1],
#                'Processed Diet': [0, 0, 1, 0, 0],

#     },
#     'Intestinal Parasites': {
#     		   'Frequent Urination' : [0, 0, 1, 0, 0],
#                'Blood in Urine' : [0, 0, 1, 0, 0],
#                'Painful Urination' : [0, 0, 1, 0, 0],
#                'Licking Genital Area' : [0, 0, 1, 0, 0],
#                'Lethargy and Weakness' : [0, 0, 0, 0, 1],
#                'Straining to Urinate' : [0, 0, 1, 0, 0],
#                'Abdominal Pain' : [0, 0, 0, 0, 1],
#                'Vomiting and Nausea' : [0, 0, 1, 0, 0],
#                'Polydipsia' : [0, 0, 1, 0, 0],
#                'Limping' : [0, 0, 1, 0, 0],
#                'Swelling members' : [0, 0, 1, 0, 0],
#                'Fever' : [0, 0, 1, 0, 0],
#                'Loss Appetite' : [0, 0, 1, 0, 0],
#                'Weight loss' : [0, 0, 0, 0, 1],
#                'PotBellied Appearance' : [0, 0, 0, 0, 1],
#                'Diarrhea' : [0, 0, 0, 0, 1],
#                'Constipation' : [0, 0, 1, 0, 0],
#                'Visible Worms' : [0, 0, 0, 0, 1],
#                'Anal Itching or Scooting' : [0, 0, 0, 0, 1],
#                'Intense itching and scratching' : [0, 0, 1, 0, 0],
#                'Hair loss or thinning of fur' : [0, 0, 1, 0, 0],
#                'Formation of small raised bumps or pustules' : [0, 0, 1, 0, 0],
#                'Irritated or weepy eyes' : [0, 0, 0, 0, 1],
#                'Restlessness and Agitation' : [0, 0, 1, 0, 0],
#                'Over-Grooming' : [0, 0, 1, 0, 0],
#                'Presence of fleas' : [0, 0, 0, 0, 1],
#                'Ear Infection' : [0, 0, 1, 0, 0],
#                'Overweight': [0, 0, 1, 0, 0],
#                'Age': [1, 1, 0, 0, 0],
#                'Vaccination updated': [0, 0, 1, 0, 0],
#                'Male': [0, 0, 1, 0, 0],
#                'Indoor': [1, 0, 0, 0, 0],
#                'Contact with other pets': [0, 0, 1, 0, 0],
#                'Neutered': [0, 0, 1, 0, 0],
#                'Start of the symptoms': [0, 0, 1, 0, 0],
#                'Processed Diet': [0, 0, 1, 0, 0],

#     },
#     'Hairball Obstruction': {
#     		   'Frequent Urination' : [0, 0, 1, 0, 0],
#                'Blood in Urine' : [0, 0, 1, 0, 0],
#                'Painful Urination' : [0, 0, 1, 0, 0],
#                'Licking Genital Area' : [0, 0, 1, 0, 0],
#                'Lethargy and Weakness' : [0, 0, 0, 0, 1],
#                'Straining to Urinate' : [0, 0, 1, 0, 0],
#                'Abdominal Pain' : [0, 0, 0, 0, 1],
#                'Vomiting and Nausea' : [0, 0, 0, 0, 1],
#                'Polydipsia' : [0, 0, 1, 0, 0],
#                'Limping' : [0, 0, 1, 0, 0],
#                'Swelling members' : [0, 0, 1, 0, 0],
#                'Fever' : [0, 0, 1, 0, 0],
#                'Loss Appetite' : [0, 0, 0, 0, 1],
#                'Weight loss' : [0, 0, 0, 0, 1],
#                'PotBellied Appearance' : [0, 0, 1, 0, 0],
#                'Diarrhea' : [0, 0, 1, 0, 0],
#                'Constipation' : [0, 0, 0, 0, 1],
#                'Visible Worms' : [0, 0, 1, 0, 0],
#                'Anal Itching or Scooting' : [0, 0, 1, 0, 0],
#                'Intense itching and scratching' : [0, 0, 1, 0, 0],
#                'Hair loss or thinning of fur' : [0, 0, 1, 0, 0],
#                'Formation of small raised bumps or pustules' : [0, 0, 1, 0, 0],
#                'Irritated or weepy eyes' : [0, 0, 0, 0, 1],
#                'Restlessness and Agitation' : [0, 0, 1, 0, 0],
#                'Over-Grooming' : [0, 0, 0, 0, 1],
#                'Presence of fleas' : [0, 0, 1, 0, 0],
#                'Ear Infection' : [0, 0, 1, 0, 0],
#                'Overweight': [0, 0, 1, 0, 0],
#                'Age': [0, 0, 1, 1, 1],
#                'Vaccination updated': [0, 0, 1, 0, 0],
#                'Male': [0, 0, 1, 0, 0],
#                'Indoor': [0, 0, 1, 0, 0],
#                'Contact with other pets': [0, 0, 1, 0, 0],
#                'Neutered': [0, 0, 1, 0, 0],
#                'Start of the symptoms': [1, 0, 0, 0, 0],
#                'Processed Diet': [0, 0, 1, 0, 0],

#     },
#     'Scabies': {
#     		   'Frequent Urination' : [0, 0, 1, 0, 0],
#                'Blood in Urine' : [0, 0, 1, 0, 0],
#                'Painful Urination' : [0, 0, 1, 0, 0],
#                'Licking Genital Area' : [0, 0, 1, 0, 0],
#                'Lethargy and Weakness' : [0, 0, 1, 0, 0],
#                'Straining to Urinate' : [0, 0, 1, 0, 0],
#                'Abdominal Pain' : [0, 0, 1, 0, 0],
#                'Vomiting and Nausea' : [0, 0, 1, 0, 0],
#                'Polydipsia' : [0, 0, 1, 0, 0],
#                'Limping' : [0, 0, 1, 0, 0],
#                'Swelling members' : [0, 0, 1, 0, 0],
#                'Fever' : [0, 0, 1, 0, 0],
#                'Loss Appetite' : [0, 0, 1, 0, 0],
#                'Weight loss' : [0, 0, 1, 0, 0],
#                'PotBellied Appearance' : [0, 0, 1, 0, 0],
#                'Diarrhea' : [0, 0, 1, 0, 0],
#                'Constipation' : [0, 0, 1, 0, 0],
#                'Visible Worms' : [0, 0, 1, 0, 0],
#                'Anal Itching or Scooting' : [0, 0, 1, 0, 0],
#                'Intense itching and scratching' : [0, 0, 0, 0, 1],
#                'Hair loss or thinning of fur' : [0, 0, 0, 0, 1],
#                'Formation of small raised bumps or pustules' : [0, 0, 1, 0, 0],
#                'Irritated or weepy eyes' : [0, 0, 0, 0, 1],
#                'Restlessness and Agitation' : [0, 0, 0, 0, 1],
#                'Over-Grooming' : [0, 0, 0, 0, 1],
#                'Presence of fleas' : [0, 0, 1, 0, 0],
#                'Ear Infection' : [0, 0, 0, 0, 1],
#                'Overweight': [0, 0, 1, 0, 0],
#                'Age': [1, 1, 0, 0, 0],
#                'Vaccination updated': [0, 0, 1, 0, 0],
#                'Male': [0, 0, 1, 0, 0],
#                'Indoor': [1, 0, 0, 0, 0],
#                'Contact with other pets': [0, 0, 0, 0, 1],
#                'Neutered': [0, 0, 1, 0, 0],
#                'Start of the symptoms': [0, 0, 1, 0, 0],
#                'Processed Diet': [0, 0, 1, 0, 0],

#     },
#     'Flea Allergy': {
#     		   'Frequent Urination' : [0, 0, 1, 0, 0],
#                'Blood in Urine' : [0, 0, 1, 0, 0],
#                'Painful Urination' : [0, 0, 1, 0, 0],
#                'Licking Genital Area' : [0, 0, 1, 0, 0],
#                'Lethargy and Weakness' : [0, 0, 1, 0, 0],
#                'Straining to Urinate' : [0, 0, 1, 0, 0],
#                'Abdominal Pain' : [0, 0, 1, 0, 0],
#                'Vomiting and Nausea' : [0, 0, 1, 0, 0],
#                'Polydipsia' : [0, 0, 1, 0, 0],
#                'Limping' : [0, 0, 1, 0, 0],
#                'Swelling members' : [0, 0, 1, 0, 0],
#                'Fever' : [0, 0, 1, 0, 0],
#                'Loss Appetite' : [0, 0, 1, 0, 0],
#                'Weight loss' : [0, 0, 1, 0, 0],
#                'PotBellied Appearance' : [0, 0, 1, 0, 0],
#                'Diarrhea' : [0, 0, 1, 0, 0],
#                'Constipation' : [0, 0, 1, 0, 0],
#                'Visible Worms' : [0, 0, 1, 0, 0],
#                'Anal Itching or Scooting' : [0, 0, 0, 0, 1],
#                'Intense itching and scratching' : [0, 0, 0, 0, 1],
#                'Hair loss or thinning of fur' : [0, 0, 0, 0, 1],
#                'Formation of small raised bumps or pustules' : [0, 0, 0, 0, 1],
#                'Irritated or weepy eyes' : [0, 0, 1, 0, 0],
#                'Restlessness and Agitation' : [0, 0, 1, 0, 0],
#                'Over-Grooming' : [0, 0, 0, 0, 1],
#                'Presence of fleas' : [0, 0, 0, 0, 1],
#                'Ear Infection' : [0, 0, 1, 0, 0],
#                'Overweight': [0, 0, 1, 0, 0],
#                'Age': [0, 0, 1, 1, 1],
#                'Vaccination updated': [0, 0, 1, 0, 0],
#                'Male': [0, 0, 1, 0, 0],
#                'Indoor': [0, 0, 1, 0, 0],
#                'Contact with other pets': [0, 0, 1, 0, 0],
#                'Neutered': [0, 0, 1, 0, 0],
#                'Start of the symptoms': [0, 0, 1, 0, 0],
#                'Processed Diet': [0, 0, 1, 0, 0],

#     },
#     'Atopic Dermatitis': {
#     		   'Frequent Urination' : [0, 0, 1, 0, 0],
#                'Blood in Urine' : [0, 0, 1, 0, 0],
#                'Painful Urination' : [0, 0, 1, 0, 0],
#                'Licking Genital Area' : [0, 0, 1, 0, 0],
#                'Lethargy and Weakness' : [0, 0, 1, 0, 0],
#                'Straining to Urinate' : [0, 0, 1, 0, 0],
#                'Abdominal Pain' : [0, 0, 1, 0, 0],
#                'Vomiting and Nausea' : [0, 0, 1, 0, 0],
#                'Polydipsia' : [0, 0, 1, 0, 0],
#                'Limping' : [0, 0, 1, 0, 0],
#                'Swelling members' : [0, 0, 1, 0, 0],
#                'Fever' : [0, 0, 1, 0, 0],
#                'Loss Appetite' : [0, 0, 1, 0, 0],
#                'Weight loss' : [0, 0, 1, 0, 0],
#                'PotBellied Appearance' : [0, 0, 1, 0, 0],
#                'Diarrhea' : [0, 0, 1, 0, 0],
#                'Constipation' : [0, 0, 1, 0, 0],
#                'Visible Worms' : [0, 0, 1, 0, 0],
#                'Anal Itching or Scooting' : [0, 0, 0, 0, 1],
#                'Intense itching and scratching' : [0, 0, 0, 0, 1],
#                'Hair loss or thinning of fur' : [0, 0, 0, 0, 1],
#                'Formation of small raised bumps or pustules' : [0, 0, 0, 0, 1],
#                'Irritated or weepy eyes' : [0, 0, 0, 0, 1],
#                'Restlessness and Agitation' : [0, 0, 1, 0, 0],
#                'Over-Grooming' : [0, 0, 1, 0, 0],
#                'Presence of fleas' : [0, 0, 1, 0, 0],
#                'Ear Infection' : [0, 0, 0, 0, 1],
#                'Overweight': [0, 0, 1, 0, 0],
#                'Age': [0, 0, 1, 1, 0],
#                'Vaccination updated': [0, 0, 1, 0, 0],
#                'Male': [0, 0, 1, 0, 0],
#                'Indoor': [0, 0, 1, 0, 0],
#                'Contact with other pets': [0, 0, 1, 0, 0],
#                'Neutered': [0, 0, 1, 0, 0],
#                'Start of the symptoms': [1, 0, 0, 0, 0],
#                'Processed Diet': [0, 0, 1, 0, 0],

#     },

#     # 'Feline Lower Urinary Tract Disease': {
#     # 		   'Frequent Urination' : [0, 0, 0, 0, 0],
#     #            'Blood in Urine' : [0, 0, 0, 0, 0],
#     #            'Painful Urination' : [0, 0, 0, 0, 0],
#     #            'Licking Genital Area' : [0, 0, 0, 0, 0],
#     #            'Lethargy and Weakness' : [0, 0, 0, 0, 0],
#     #            'Straining to Urinate' : [0, 0, 0, 0, 0],
#     #            'Abdominal Pain' : [0, 0, 0, 0, 0],
#     #            'Vomiting and Nausea' : [0, 0, 0, 0, 0],
#     #            'Polydipsia' : [0, 0, 0, 0, 0],
#     #            'Limping' : [0, 0, 0, 0, 0],
#     #            'Swelling members' : [0, 0, 0, 0, 0],
#     #            'Fever' : [0, 0, 0, 0, 0],
#     #            'Loss Appetite' : [0, 0, 0, 0, 0],
#     #            'Weight loss' : [0, 0, 0, 0, 0],
#     #            'PotBellied Appearance' : [0, 0, 0, 0, 0],
#     #            'Diarrhea' : [0, 0, 0, 0, 0],
#     #            'Constipation' : [0, 0, 0, 0, 0],
#     #            'Visible Worms' : [0, 0, 0, 0, 0],
#     #            'Anal Itching or Scooting' : [0, 0, 0, 0, 0],
#     #            'Intense itching and scratching' : [0, 0, 0, 0, 0],
#     #            'Hair loss or thinning of fur' : [0, 0, 0, 0, 0],
#     #            'Formation of small raised bumps or pustules' : [0, 0, 0, 0, 0],
#     #            'Irritated or weepy eyes' : [0, 0, 0, 0, 0],
#     #            'Restlessness and Agitation' : [0, 0, 0, 0, 0],
#     #            'Over-Grooming' : [0, 0, 0, 0, 0],
#     #            'Presence of fleas' : [0, 0, 0, 0, 0],
#     #            'Ear Infection' : [0, 0, 0, 0, 0],
#     #            'Overweight': [0, 0, 0, 0, 0],
#     #            'Age': [0, 0, 0, 0, 0
#     #            'Male': [0, 0, 0, 0, 0],
#     #            'Indoor': [0, 0, 0, 0, 0],
#     #            'Contact with other pets': [0, 0, 0, 0, 0],
#     #            'Neutered': [0, 0, 0, 0, 0],
#     #            'Symptoms started Less than a day': [0, 0, 0, 0, 0],
#     #            'Symptoms started in one day to a week': [0, 0, 0, 0, 0],
#     #            'Symptoms started in a week to a month': [0, 0, 0, 0, 0],
#     #            'Symptoms started more than a month': [0, 0, 0, 0, 0],
#     #            'Processed Diet': [0, 0, 0, 0, 0],
#     #            'Natural Diet': [0, 0, 0, 0, 0],
#     # },
# }





# # file = open("TESTEDB.txt", 'w')
# # for disease, symptoms in DiseaseRules.items():
# #     for symptom, values in symptoms.items():
            
# #         string = str(DicDis[disease]) + " | " + str(DicSym[symptom]) + " | " + str(values[0]) + " | " + str(values[1]) + " | " + str(values[2]) + " | " + str(values[3]) + " | " + str(values[4]) + "\n"
# #         print(string)
# #         file.write(string)

# # file.close()

# # file = open("DiseaseRules.csv", 'w')
# # for disease, symptoms in DiseaseRules.items():
# #     for symptom, values in symptoms.items():
            
# #         string = str(DicDis[disease]) + "," + str(DicSym[symptom]) + "," + str(values[0]) + "," + str(values[1]) + "," + str(values[2]) + "," + str(values[3]) + "," + str(values[4]) + "\n"        
# #         file.write(string)

# # file.close()
        





    
