export { default as HomePage } from "./HomePage";
export { default as LandingPage } from "./LandingPage";
export { default as LoginPage } from "./LoginPage";
export { default as MapPage } from "./MapPage";
export { default as RegisterPage } from "./RegisterPage";
export { default as SymptomPage } from "./SymptomPage";
export { default as UserPage } from "./UserPage";
export { default as VideoPage } from "./VideoPage";
export { default as AboutPage } from "./AboutPage";
// export { default as ChatPage } from "./ChatPage";
