# Symptoms Type (Discrete, Continuous)
AnswerValues = {
    '1' : 0.00,
    '2' : 0.25,
    '3' : 0.50,
    '4' : 0.75,
    '5' : 1.00,
}

Allspecialty = ['Urinary']

AllDiseases = [
               {'name': 'Urethal Obstruction', 'specialty':'Urinary'},
               {'name': 'Feline Lower Urinary Tract Disease', 'specialty':'Urinary'},
               {'name': 'Renal Disease', 'specialty':'Urinary'},
               {'name': 'Luxation', 'specialty':'Musculoskeletal'},
               {'name': 'Panleukopenia', 'specialty':'Gastrointestinal'},
               {'name': 'Intestinal Parasites', 'specialty':'Gastrointestinal'},
               {'name': 'Hairball Obstruction', 'specialty':'Gastrointestinal'},
               {'name': 'Scabies', 'specialty':'Dermatology'},
               {'name': 'Flea Alergy', 'specialty':'Dermatology'},
               {'name': 'Atopic Dermatitis', 'specialty':'Dermatology'},
              ]

AllVariables = [
                {'name':'Frequent Urination' , 'type':'symptom', 'specialty':['Urinary']},
                {'name':'Blood in Urine' , 'type':'symptom', 'specialty':['Urinary']},
                {'name':'Painful Urination' , 'type':'symptom', 'specialty':['Urinary']},
                {'name':'Licking Genital Area' , 'type':'symptom', 'specialty':['Urinary', 'Gastrointestinal']},
                {'name':'Lethargy and Weakness' , 'type':'symptom', 'specialty':['Urinary']},
                {'name':'Straining to Urinate' , 'type':'symptom', 'specialty':['Urinary', 'Gastrointestinal']},
                {'name':'Abdominal Pain' , 'type':'symptom', 'specialty':['Urinary', 'Gastrointestinal']},
                {'name':'Vomiting and Nausea' , 'type':'symptom', 'specialty':['Urinary', 'Gastrointestinal']},
                {'name':'Polydipsia' , 'type':'symptom', 'specialty':['Musculoskeletal']},
                {'name':'Limping' , 'type':'symptom', 'specialty':['Urinary', 'Musculoskeletal']},
                {'name':'Swelling members' , 'type':'symptom', 'specialty':['Gastrointestinal']},
                {'name':'Fever' , 'type':'symptom', 'specialty':['Urinary' ,'Gastrointestinal']},
                {'name':'Loss Appetite' , 'type':'symptom', 'specialty':['Urinary' ,'Gastrointestinal']},
                {'name':'Weight loss' , 'type':'symptom', 'specialty':['Urinary','Gastrointestinal']},
                {'name':'PotBellied Appearance' , 'type':'symptom', 'specialty':['Gastrointestinal']},
                {'name':'Diarrhea' , 'type':'symptom', 'specialty':['Gastrointestinal']},
                {'name':'Constipation' , 'type':'symptom', 'specialty':['Gastrointestinal']},
                {'name':'Visible Worms' , 'type':'symptom', 'specialty':['Gastrointestinal', 'Dermatology']},
                {'name':'Anal Itching or Scooting' , 'type':'symptom', 'specialty':['Dermatology', 'Gastrointestinal']},
                {'name':'Intense itching and scratching' , 'type':'symptom', 'specialty':['Dermatology']},
                {'name':'Hair loss or thinning of fur' , 'type':'symptom', 'specialty':['Dermatology']},
                {'name':'Formation of small raised bumps or pustules' , 'type':'symptom', 'specialty':['Dermatology']},
                {'name':'Irritated or weepy eyes' , 'type':'symptom', 'specialty':['Dermatology', 'Gastrointestinal']},
                {'name':'Restlessness and Agitation' , 'type':'symptom', 'specialty':['Dermatology', 'Urinary']},
                {'name':'Over-Grooming' , 'type':'symptom', 'specialty':['Dermatology', 'Gastrointestinal']},
                {'name':'Ear Infection' , 'type':'symptom', 'specialty':['Dermatology']},
                {'name':'Presence of fleas' , 'type':'animalatribute', 'specialty':[]},
                {'name':'Overweight' , 'type':'animalatribute', 'specialty':[]},
                {'name':'Kitten' , 'type':'animalatribute', 'specialty':[]},
                {'name':'Young adult' , 'type':'animalatribute', 'specialty':[]},
                {'name':'Adult' , 'type':'animalatribute', 'specialty':[]},
                {'name':'Mature Adult' , 'type':'animalatribute', 'specialty':[]},
                {'name':'Old' , 'type':'animalatribute', 'specialty':[]},
                {'name':'Vaccination updated' , 'type':'animalatribute', 'specialty':[]},
                {'name':'Male' , 'type':'animalatribute', 'specialty':[]},
                {'name':'Female' , 'type':'animalatribute', 'specialty':[]},
                {'name':'Indoor' , 'type':'animalatribute', 'specialty':[]},
                {'name':'Outdoor' , 'type':'animalatribute', 'specialty':[]},
                {'name':'Contact with other pets' , 'type':'animalatribute', 'specialty':[]},
                {'name':'Neutered' , 'type':'animalatribute', 'specialty':[]},
                {'name':'Symptoms started Less than a day' , 'type':'symptomatribute', 'specialty':[]},
                {'name':'Symptoms started in one day to a week' , 'type':'symptomatribute', 'specialty':[]},
                {'name':'Symptoms started in a week to a month' , 'type':'symptomatribute', 'specialty':[]},
                {'name':'Symptoms started more than a month' , 'type':'symptomatribute', 'specialty':[]},
                {'name':'Processed Diet' , 'type':'animalatribute', 'specialty':[]},
                {'name':'Natural Diet' , 'type':'animalatribute', 'specialty':[]},
              ]
