"""empty message

Revision ID: 38c1234a4939
Revises: 
Create Date: 2023-08-12 21:24:30.543813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c1234a4939'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diseases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('pets', sa.JSON(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('appointment_history', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(length=100), nullable=False),
    sa.Column('question', sa.String(length=200), nullable=False),
    sa.Column('specialty', sa.String(length=200), nullable=True),
    sa.Column('defaultQuestion', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=False),
    sa.Column('outdoor', sa.Boolean(), nullable=False),
    sa.Column('neutered', sa.Boolean(), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('diet', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_answers_count',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('diseasesVariables_id', sa.Integer(), nullable=False),
    sa.Column('no', sa.Integer(), nullable=True),
    sa.Column('probablyNot', sa.Integer(), nullable=True),
    sa.Column('iDontKnow', sa.Integer(), nullable=True),
    sa.Column('probablyYes', sa.Integer(), nullable=True),
    sa.Column('yes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ),
    sa.ForeignKeyConstraint(['diseasesVariables_id'], ['variables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('diagnosis', sa.JSON(), nullable=True),
    sa.Column('field', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diary')
    op.drop_table('appointments')
    op.drop_table('users_answers_count')
    op.drop_table('pets')
    op.drop_table('variables')
    op.drop_table('user')
    op.drop_table('diseases')
    # ### end Alembic commands ###
